"""Regenerate every figure from committed result artefacts.

`Makefile` has advertised `make figures` since the repository was created and the script it
calls did not exist, which is the same defect ADR-0014 recorded for `make gates`: a
documented entry point that had never been run. This is that script.

Two rules shape it.

**A figure is built only from a committed artefact, never from a live computation.** The
figure and the number in the text then come from the same file, so they cannot drift apart,
and a figure can be regenerated by anyone with the repository and no compute.

**A missing artefact is reported, not fatal.** Most of the grid is unrun at any given moment,
and a script that dies on the first gap would mean the only way to see any figure is to have
finished everything. Each figure says whether it was drawn or skipped and why, and the exit
code is zero either way; the check that every *claimed* artefact exists is
`scripts/check_claims.py`, which is a different job.

**The numbering here is not the execution plan's numbering, and that has to be resolved
before anything is written.** Plan v4 section 5.2 reserves seven figure slots. The labels in
this script were chosen for what the rebuild could actually produce, and they collide:

| Plan slot | Plan content | Where that content lives here |
|---|---|---|
| F1 | Correspondence and circuit schematic | not built, it is a drawing rather than a result |
| F2 | Validation overlay, analytic against exact against Trotter | not built |
| F3 | Error-threshold transition | **F4** here |
| F4 | Spectral gap and conditioning across ruggedness, mu and L | **F1** here |
| F5 | Route A against Route B, accuracy and resources | not built; **F5** here is the MPO bond dimension |
| F6 | Hardware, noiseless to raw to mitigated | not built, needs WP8 |
| F7 | Boundary map and chi-hardness contours | **F7** here, the one slot that agrees |

Only F7 means the same thing in both. Two figures here, Pauli sparsity and MPO bond
dimension, have no slot in the plan at all, because they answer questions the plan did not
anticipate asking. Renumbering is deliberately not done unilaterally: the plan is the
pre-registered document, the manuscript will cite its numbering, and reassigning F1 or F5
is a choice about what the paper argues rather than a tidy-up. Recorded as open item 10.

    python scripts/make_figures.py
    python scripts/make_figures.py --list
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
FIGURES = ROOT / "figures"


def load(relative: str) -> dict[str, Any] | None:
    path = RESULTS / relative
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _finish(figure, axes, name: str) -> str:
    figure.tight_layout()
    target = FIGURES / name
    figure.savefig(target, dpi=200)
    plt.close(figure)
    return str(target.relative_to(ROOT))


def figure_gap_closing() -> tuple[str, str]:
    """How the spectral gap closes at the error threshold, and where float64 stops working.

    The second series is the point of the figure as much as the first. A fine grid reads the
    minimum as 2260 times too large at L = 48; plotting both makes the extended-precision
    path visibly necessary rather than a claim in a docstring.
    """
    record = load("wp1/g_1.json")
    if record is None:
        return "skipped", "results/wp1/g_1.json is not present"
    closing = record["measured"]["gap_map"]["gap_closing_at_threshold"]
    sizes = [row["L"] for row in closing]
    exact = [row["min_gap"] for row in closing]
    grid = [row["min_gap_off_the_fine_grid"] for row in closing]
    base = record["measured"]["gap_map"]["closing_base"]
    prefactor = record["measured"]["gap_map"]["closing_prefactor"]

    figure, axes = plt.subplots(figsize=(6.0, 4.2))
    axes.semilogy(sizes, exact, "o-", label="arbitrary precision")
    axes.semilogy(sizes, grid, "s--", label="1500-point grid", alpha=0.7)
    axes.semilogy(
        sizes,
        [prefactor * base**n for n in sizes],
        ":",
        color="black",
        label=f"${prefactor:.3f}\\times{base:.5f}^L$",
    )
    axes.set_xlabel("system size $L$")
    axes.set_ylabel("spectral gap at the threshold")
    axes.set_title("The gap closes exponentially, and a grid cannot see it")
    axes.legend(frameon=False)
    axes.grid(alpha=0.3)
    return "drawn", _finish(figure, axes, "F1_gap_closing.png")


def figure_barren_plateau() -> tuple[str, str]:
    """Gradient-variance decay, all six measured combinations rather than the gate's one."""
    record = load("wp_r/g_r_9.json")
    if record is None:
        return "skipped", "results/wp_r/g_r_9.json is not present"
    series = record["measured"]["variance_series"]
    fits = record["measured"]["all_fits"]
    gate = record["measured"]["gate_statistic"]

    figure, axes = plt.subplots(figsize=(6.4, 4.2))
    for landscape, statistics in series.items():
        for statistic, values in statistics.items():
            key = f"{landscape}_{statistic}"
            sizes = list(range(2, 2 + len(values)))
            axes.semilogy(
                sizes,
                values,
                "o-" if key == gate else ".--",
                linewidth=2.0 if key == gate else 1.0,
                alpha=1.0 if key == gate else 0.6,
                label=f"{key} ({fits[key]['base']:.4f})" + (" ← gate" if key == gate else ""),
            )
    axes.set_xlabel("system size $L$")
    axes.set_ylabel("variance of the McLachlan force")
    axes.set_title("Gradient variance decays exponentially, base near 0.54")
    axes.legend(frameon=False, fontsize=7)
    axes.grid(alpha=0.3)
    return "drawn", _finish(figure, axes, "F2_barren_plateau.png")


def figure_pauli_sparsity() -> tuple[str, str]:
    """The sparse spin convention against the projector form, which is a factor of 152."""
    record = load("wp_r/g_r_10.json")
    if record is None:
        return "skipped", "results/wp_r/g_r_10.json is not present"
    ratios = record["measured"]["ratio_by_size"]
    sizes = sorted(int(k) for k in ratios)

    figure, axes = plt.subplots(figsize=(6.0, 4.2))
    axes.semilogy(sizes, [ratios[str(n)] for n in sizes], "o-")
    axes.axhline(
        record["threshold"]["value"],
        linestyle=":",
        color="black",
        label=f"registered threshold, {record['threshold']['value']:.0f}",
    )
    axes.set_xlabel("system size $L$")
    axes.set_ylabel("Pauli terms, projector form / sparse form")
    axes.set_title("Why the spin convention is a factor of 152 at $L=12$")
    axes.legend(frameon=False)
    axes.grid(alpha=0.3)
    return "drawn", _finish(figure, axes, "F3_pauli_sparsity.png")


def figure_error_threshold() -> tuple[str, str]:
    """The localisation transition, and how it sharpens with size."""
    record = load("wp_r/g_r_4.json")
    if record is None:
        return "skipped", "results/wp_r/g_r_4.json is not present"
    scaling = record["measured"].get("sharp_peak_gap_scaling")
    if not scaling:
        return "skipped", "g_r_4.json has no sharp_peak_gap_scaling series"

    figure, axes = plt.subplots(1, 2, figsize=(9.5, 4.0))
    sizes = [row["L"] for row in scaling]
    axes[0].semilogy(sizes, [row["min_gap"] for row in scaling], "o-")
    axes[0].set_xlabel("system size $L$")
    axes[0].set_ylabel("minimum gap over the sweep")
    axes[0].set_title("Gap at the threshold")
    axes[0].grid(alpha=0.3)

    axes[1].plot(sizes, [row["mu_at_min_gap"] * row["L"] for row in scaling], "s-")
    axes[1].axhline(1.0, linestyle=":", color="black", label=r"$\mu_c L = h$")
    axes[1].set_xlabel("system size $L$")
    axes[1].set_ylabel(r"$\mu^* L$ / peak height")
    # Not "converges". G-R.4 locates the minimum on a coarse sweep grid, so these points
    # carry a quantisation of a few percent and the series is not monotone at small L.
    # The clean convergence is in G-1, which locates the minimum by arbitrary-precision
    # search and gets 1.0347 at L = 32 and 1.0080 at L = 128. Claiming convergence from
    # this panel would be reading through the quantisation rather than around it.
    axes[1].set_title("Threshold location, grid-limited at small $L$")
    axes[1].legend(frameon=False)
    axes[1].grid(alpha=0.3)
    return "drawn", _finish(figure, axes, "F4_error_threshold.png")


def figure_mpo_bond_dimension() -> tuple[str, str]:
    """Where a matrix product is structurally disadvantaged, stated rather than exploited."""
    record = load("wp6/g_6_3.json")
    if record is None:
        return "skipped", "results/wp6/g_6_3.json is not present"
    cases = [c for c in record["cases"] if c["L"] == max(c2["L"] for c2 in record["cases"])]
    by_family: dict[str, list[int]] = {}
    for case in cases:
        name = case["family"] + "".join(
            f" {k}={case[k]}" for k in ("K", "roughness", "block_size") if k in case
        )
        by_family.setdefault(name, []).append(case["mpo_bond_dimension"])
    names = sorted(by_family, key=lambda n: max(by_family[n]))
    values = [max(by_family[n]) for n in names]

    figure, axes = plt.subplots(figsize=(7.0, 4.4))
    axes.barh(names, values)
    axes.axvline(
        cases[0]["middle_cut_ceiling"],
        linestyle=":",
        color="black",
        label=f"ceiling, {cases[0]['middle_cut_ceiling']}",
    )
    axes.set_xlabel("MPO bond dimension at the middle cut")
    axes.set_title(f"Operator cost per family, $L={cases[0]['L']}$")
    axes.legend(frameon=False)
    axes.grid(alpha=0.3, axis="x")
    return "drawn", _finish(figure, axes, "F5_mpo_bond_dimension.png")


def figure_boundary_map() -> tuple[str, str]:
    """WP7's central figure: where each method holds accuracy across the mutation axis.

    Section 11.4 makes total variation the deciding metric where it disagrees with cosine,
    because it is the less flattering one, so total variation is what is plotted. Cosine sits
    at 1.000 across most of this grid while total variation still separates the methods,
    which is the disagreement that rule was written for.

    A method that is inapplicable in a cell is drawn as a gap, not as a zero. Baseline B
    refuses every rugged cell by design, and plotting that refusal as poor accuracy would
    invert its meaning.
    """
    import json

    for candidate in ("wp7/sweep_registered.jsonl", "_local/sweep_local.jsonl"):
        stream = RESULTS / candidate
        if stream.is_file():
            break
    else:
        return "skipped", "no sweep stream under results/"

    rows = [
        json.loads(line) for line in stream.read_text(encoding="utf-8").splitlines() if line.strip()
    ]
    if not rows:
        return "skipped", f"{stream.name} is empty"

    families = sorted({r["family"] for r in rows})
    methods = sorted({m for r in rows for m in r["methods"]})

    # One colour per method, fixed across panels. Letting matplotlib assign them per panel
    # means a method that is inapplicable in one family shifts every colour after it, so the
    # same colour denotes different methods in different panels while a single legend claims
    # otherwise. That is a figure that misleads rather than one that is merely ugly.
    palette = dict(zip(methods, plt.rcParams["axes.prop_cycle"].by_key()["color"], strict=False))

    figure, axes = plt.subplots(
        1, len(families), figsize=(4.2 * len(families), 4.0), sharey=True, squeeze=False
    )

    for column, family in enumerate(families):
        panel = axes[0][column]
        for method in methods:
            points = [
                (r["mu_over_mu_c"], r["methods"][method].get("total_variation"))
                for r in rows
                if r["family"] == family and r["methods"].get(method, {}).get("applicable")
            ]
            points = [(x, y) for x, y in points if y is not None]
            if not points:
                continue
            points.sort()
            panel.semilogy(
                [x for x, _ in points],
                [max(y, 1e-16) for _, y in points],
                "o-",
                color=palette[method],
                label=method.replace("baseline_", "").replace("_", " "),
            )
        panel.axvline(1.0, linestyle=":", color="black", alpha=0.6)
        panel.set_title(family)
        panel.set_xlabel(r"$\mu / \mu_c$")
        panel.grid(alpha=0.3)
    axes[0][0].set_ylabel("total variation from the reference")

    # Legend built from every method in the sweep, not from whichever panel happened to be
    # drawn last, so a method absent from that panel still appears.
    handles = [
        plt.Line2D(
            [], [], color=palette[m], marker="o", label=m.replace("baseline_", "").replace("_", " ")
        )
        for m in methods
    ]
    figure.legend(handles=handles, frameon=False, fontsize=8, loc="lower center", ncol=len(methods))
    figure.subplots_adjust(bottom=0.24)
    figure.suptitle(
        f"Accuracy across the mutation axis, $L={rows[0]['L']}$ "
        f"(gaps are inapplicable, not inaccurate)"
    )
    figure.savefig(FIGURES / "F7_boundary_map.png", dpi=200)
    plt.close(figure)
    return "drawn", "figures/F7_boundary_map.png"


FIGURES_TO_BUILD: dict[str, Callable[[], tuple[str, str]]] = {
    "F1 gap closing": figure_gap_closing,
    "F2 barren plateau": figure_barren_plateau,
    "F3 Pauli sparsity": figure_pauli_sparsity,
    "F4 error threshold": figure_error_threshold,
    "F5 MPO bond dimension": figure_mpo_bond_dimension,
    "F7 boundary map": figure_boundary_map,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true")
    arguments = parser.parse_args()

    if arguments.list:
        for name in FIGURES_TO_BUILD:
            print(name)
        return 0

    FIGURES.mkdir(exist_ok=True)
    drawn, skipped = 0, 0
    for name, builder in FIGURES_TO_BUILD.items():
        try:
            status, detail = builder()
        except Exception as error:  # one broken figure must not hide the others
            print(f"  {name:26s} ERROR   {error!r}")
            skipped += 1
            continue
        if status == "drawn":
            drawn += 1
            print(f"  {name:26s} drawn   {detail}")
        else:
            skipped += 1
            print(f"  {name:26s} skipped {detail}")

    print(f"\n{drawn} drawn, {skipped} skipped")
    if skipped:
        print(
            "Skipped figures are waiting on artefacts, not broken. Run the gate that "
            "produces each one, then re-run this."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
